#+title: Category Theory
#+author: Bailey Wickham
#+export_file_name: index
#+setupfile: comfy_inline.theme

* Introduction
This document is part of my notes on my category theory senior project under [[https://www.mathgenealogy.org/id.php?id=110360][Dr. Robert Easton]]. The document is written in org hosted on github [[https://github.com/baileywickham/CategoryTheory][here]].

Following a basic introduction to category theory, I'm interested in studying some advanced topic, which topic yet, I don't know. I'm interested in Algebraic Geometry, sheafs, schemes, topoi, stacks etc. I'm also interested in \infty-Catgeories. And perfectoid spaces, but those are mostly unrelated, though I haven't seen a category theoretic perspective on them. 


* Interesting Resources
** TODO Papers to read, or things to do
- [[https://homes.cs.washington.edu/~pedrod/papers/mlc00c.pdf][Version Space Algebras]] A paper I came across in my Grad PL course. A VSA is heavily informed by category theoretic definitions, but there were no direct mentions of them. I'll have to look around and see if there is a formalism for it. Otherwise it could be fun to translate the paper into category theoretic
  formalisms. Computational category theory is a funny idea.
- [[https://www.ams.org/notices/200808/tx080800949p.pdf][What is an \infty-Category]] A what is article by Lurie. I should read through and take notes on this one. 

 
** Online resources
This is sort of ordered by interest, but losely

- [[https://golem.ph.utexas.edu/category/][The n-Category Cafe]] Where all the cool math people hangout 
- [[https://ncatlab.org/nlab/show/mathematics][nLab]] The best and most consistent online resource I've found for higher category theory. Somewhat unreadable.  
- [[https://www.math3ma.com/categories/category-theory][Math3ma]] Generally a very readable version of category theoretic concepts 
- [[https://bartoszmilewski.com/2015/07/29/representable-functors/][Representable Functors from a CS point of view]]
 
** Books
- [[https://www.maths.ed.ac.uk/~tl/][Leinster]] Tom Leinster has a book on basic category theory which is good, and a book on higher category theory I haven't touched. 
- [[https://stacks.math.columbia.edu/tag/0011][The Stacks project]] A open source textbook for the theory of stacks
- [[https://kerodon.net/tag/0001][The Kerodon project]] Ran by Lurie, higher homotopy version of the stacks project. 


* Mac Lane
[[file:chapters/chapter1.org][Notes]]

** Chapter 1  
- Arrow categories vs Set categories? What are the meaningful differences here? When will I need to define which I am working in? Small and large categories still apply here, correct?
- Are arrow only categories interesting? Is this the start of the perspective I should be thinking in? 
- Can a functor from a category to itself be regarded as a subset of the morphisms on that category? I'm thinking of the power set functor, where you don't need to realize the functor definiton to consider the power set. 
  - What about self functors? When is a general morphism a functor. Like the commutator vs center map. Is there a general way to tell when you have a functor? 
- How does using a Universe or Class get around the same large/small problem with *Cat*? I should be able to answer this based on the textbook. 
  - *Cat* is the category of small categories. The problem still arrises when considering the category of classes etc. 
- What is the use of arrow only categories? Are they related to yoneda and hom functors?
